name: Build apk

on: [push]

jobs:

  generate-apk:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi --no-tree-shake-icons
      - run: flutter build apk --split-per-abi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
           name: arm64-release
           path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
        
